[package]
name = "pathfinder"
version = "2.0.0"
edition = "2024"

[lib]
path = "pathfinder.rs"

[dependencies]
serde = { workspace = true }
fnv = { workspace = true }
vector = { workspace = true }
core_util = { workspace = true }
itertools = { workspace = true }
