[workspace]

resolver = "2"

members = [
	"corelibs/fixed_str",
	"corelibs/vector",
	"corelibs/core_util",
	"engine",
	"gamecore",
	"webshell",
]

[workspace.dependencies]
core_util = { path = "corelibs/core_util" }
engine = { path = "engine" }
fixed_str = { path = "corelibs/fixed_str" }
gamecore = { path = "gamecore" }
vector = { path = "corelibs/vector" }

bytemuck = "1"
anyhow = "1"
fnv = "1"
log = "0.4"
num-traits = "0.2"
serde = { version = "1", features = ["derive"] }
