[workspace]

resolver = "2"

members = [
	"corelibs/fixed_str",
	"corelibs/vector",
	"corelibs/core_util",
	"corelibs/geometry",
	"corelibs/matrix",
	"gamecore",
	"webshell",
	"proc_macros",
	"proc_macros_impl",
	"corelibs/memkeep",
]

[workspace.dependencies]
core_util = { path = "corelibs/core_util" }
fixed_str = { path = "corelibs/fixed_str" }
geometry = { path = "corelibs/geometry" }
matrix = { path = "corelibs/matrix" }
gamecore = { path = "gamecore" }
vector = { path = "corelibs/vector" }
proc_macros = { path = "proc_macros" }

anyhow = "1"
base64 = "0.22"
bincode = { version = "2", features = ["serde"] }
bytemuck = "1"
fnv = "1"
googletest = "0.14"
itertools = "0.14"
log = "0.4"
num-traits = "0.2"
rand = { version = "0.8", default-features = false }
rand_chacha = "0.3"
serde = { version = "1", features = ["derive"] }
