[workspace]

resolver = "2"

members = [
	"corelibs/fixed_str",
	"corelibs/vector",
	"corelibs/core_util",
	"engine",
	"gamecore",
	"webshell",
	"proc_macros",
	"proc_macros_impl",
]

[workspace.dependencies]
core_util = { path = "corelibs/core_util" }
engine = { path = "engine" }
fixed_str = { path = "corelibs/fixed_str" }
gamecore = { path = "gamecore" }
vector = { path = "corelibs/vector" }
proc_macros = { path = "proc_macros" }

anyhow = "1"
bytemuck = "1"
fnv = "1"
log = "0.4"
num-traits = "0.2"
rand = { version = "0.8", default-features = false }
rand_chacha = "0.3"
serde = { version = "1", features = ["derive"] }
