[workspace]

resolver = "2"

members = [
	"corelibs/cel",
	"corelibs/core_util",
	"corelibs/fixed_str",
	"corelibs/geometry",
	"corelibs/matrix",
	"corelibs/memkeep",
	"corelibs/memkeep",
	"corelibs/pathfinder",
	"corelibs/vector",
	"gamecore",
	"proc_macros",
	"proc_macros_impl",
	"webshell",
]

[workspace.dependencies]
cel = { path = "corelibs/cel" }
pathfinder = { path = "corelibs/pathfinder" }
core_util = { path = "corelibs/core_util" }
fixed_str = { path = "corelibs/fixed_str" }
gamecore = { path = "gamecore" }
geometry = { path = "corelibs/geometry" }
matrix = { path = "corelibs/matrix" }
memkeep = { path = "corelibs/memkeep" }
proc_macros = { path = "proc_macros" }
vector = { path = "corelibs/vector" }

anyhow = "1"
base64 = "0.22"
bincode = { version = "2", features = ["serde"] }
bytemuck = "1"
fnv = "1"
ron = "0.10"
googletest = "0.14"
itertools = "0.14"
log = "0.4"
num-traits = "0.2"
num_enum = "0.7"
rand = { version = "0.8", default-features = false }
rand_chacha = "0.3"
serde = { version = "1", features = ["derive"] }
