[package]
name = "engine"
version = "6.0.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
core_util = { workspace = true }
fixed_str = { workspace = true }
fnv = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
vector = { workspace = true }
