[package]
name = "cel"
version = "2.0.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
vector = { workspace = true }
core_util = { workspace = true }

[dev-dependencies]
googletest = { workspace = true }
